#cloud-config

# Docker-in-Podman Installation
# Runs Docker Engine inside a privileged Podman container
# Use case: Testing Docker workflows in isolated Podman-managed environments
# Note: Uses root Podman for proper privileged container support
# Pinned versions for stability (Ubuntu 24.04 LTS)
# Podman: 4.9.3 | Docker DinD image: 27.3

package_update: true
package_upgrade: true

packages:
  - podman=4.9.3+ds1-1ubuntu0.2
  - curl
  - wget
  - git
  - uidmap
  - slirp4netns
  - fuse-overlayfs

write_files:
  - path: /etc/containers/registries.conf
    permissions: '0644'
    content: |
      unqualified-search-registries = ["docker.io"]
      
      [[registry]]
      location = "docker.io"
      
      [[registry]]
      location = "quay.io"
      
      [[registry]]
      location = "gcr.io"

  - path: /home/ubuntu/Containerfile.dind
    permissions: '0644'
    content: |
      FROM docker:27.3-dind
      
      # Install additional tools
      RUN apk add --no-cache \
          bash \
          curl \
          git \
          jq
      
      # Create workspace directory
      RUN mkdir -p /workspace
      WORKDIR /workspace
      
      # Default command starts dockerd
      CMD ["dockerd-entrypoint.sh"]

  - path: /home/ubuntu/start-docker-container.sh
    permissions: '0755'
    content: |
      #!/bin/bash
      # Start Docker-in-Podman container (uses root Podman for privileged support)
      
      CONTAINER_NAME="docker-engine"
      
      # Check if container already exists
      if sudo podman container exists $CONTAINER_NAME 2>/dev/null; then
          echo "Container '$CONTAINER_NAME' already exists"
          if ! sudo podman ps --format "{{.Names}}" | grep -q "^${CONTAINER_NAME}$"; then
              echo "Starting existing container..."
              sudo podman start $CONTAINER_NAME
          else
              echo "Container is already running"
          fi
      else
          echo "Creating and starting Docker-in-Podman container..."
          sudo podman run -d \
              --name $CONTAINER_NAME \
              --privileged \
              --cgroupns=host \
              -v docker-data:/var/lib/docker \
              -v /home/ubuntu/workspace:/workspace \
              --restart unless-stopped \
              docker.io/library/docker:27.3-dind \
              dockerd --host=unix:///var/run/docker.sock --host=tcp://0.0.0.0:2375 --tls=false
      fi
      
      # Wait for Docker daemon to be ready
      echo "Waiting for Docker daemon to start..."
      for i in {1..30}; do
          if sudo podman exec $CONTAINER_NAME docker info &>/dev/null; then
              echo "Docker daemon is ready!"
              exit 0
          fi
          sleep 1
      done
      
      echo "Warning: Docker daemon may not be fully ready"
      exit 1

  - path: /home/ubuntu/docker
    permissions: '0755'
    content: |
      #!/bin/bash
      # Docker CLI wrapper - executes docker commands inside the Podman container
      CONTAINER_NAME="docker-engine"
      
      if ! sudo podman ps --format "{{.Names}}" | grep -q "^${CONTAINER_NAME}$"; then
          echo "Error: Docker container '$CONTAINER_NAME' is not running"
          echo "Start it with: ~/start-docker-container.sh"
          exit 1
      fi
      
      sudo podman exec -i $CONTAINER_NAME docker "$@"

  - path: /home/ubuntu/docker-compose
    permissions: '0755'
    content: |
      #!/bin/bash
      # Docker Compose wrapper - executes docker compose inside the Podman container
      CONTAINER_NAME="docker-engine"
      
      if ! sudo podman ps --format "{{.Names}}" | grep -q "^${CONTAINER_NAME}$"; then
          echo "Error: Docker container '$CONTAINER_NAME' is not running"
          echo "Start it with: ~/start-docker-container.sh"
          exit 1
      fi
      
      sudo podman exec -i $CONTAINER_NAME docker compose "$@"

  - path: /home/ubuntu/test-docker-in-podman.sh
    permissions: '0755'
    content: |
      #!/bin/bash
      echo "=== Testing Docker-in-Podman Installation ==="
      echo ""
      echo "Podman version (host):"
      podman --version
      echo ""
      echo "Docker container status:"
      podman ps --filter name=docker-engine
      echo ""
      echo "Docker version (inside container):"
      ~/docker --version
      echo ""
      echo "Running hello-world in Docker (inside Podman):"
      ~/docker run --rm hello-world:linux
      echo ""
      echo "=== Docker-in-Podman Test Complete ==="

  - path: /home/ubuntu/.config/containers/containers.conf
    permissions: '0644'
    content: |
      [containers]
      log_driver = "k8s-file"
      
      [engine]
      cgroup_manager = "systemd"
      events_logger = "journald"

runcmd:
  # Configure subuid and subgid for rootless containers
  - usermod --add-subuids 100000-165535 --add-subgids 100000-165535 ubuntu
  
  # Enable linger for ubuntu user (allows user services without active login)
  - loginctl enable-linger ubuntu
  
  # Ensure home directory has correct ownership
  - chown -R ubuntu:ubuntu /home/ubuntu
  
  # Create required directories
  - mkdir -p /home/ubuntu/.config/containers
  - mkdir -p /home/ubuntu/.config/systemd/user/default.target.wants
  - mkdir -p /home/ubuntu/.local/share/containers/storage
  - mkdir -p /home/ubuntu/.cache
  - mkdir -p /home/ubuntu/workspace
  
  # Set proper ownership
  - chown -R ubuntu:ubuntu /home/ubuntu/.config
  - chown -R ubuntu:ubuntu /home/ubuntu/.local
  - chown -R ubuntu:ubuntu /home/ubuntu/.cache
  - chown -R ubuntu:ubuntu /home/ubuntu/workspace
  
  # Enable podman socket for ubuntu user
  - |
    sudo -u ubuntu bash -c '
    export XDG_RUNTIME_DIR=/run/user/$(id -u ubuntu)
    systemctl --user daemon-reload
    systemctl --user enable podman.socket
    systemctl --user start podman.socket
    '
  
  # Enable system-wide podman socket
  - systemctl enable --now podman.socket
  
  # Add docker wrapper to PATH
  - echo 'export PATH=$HOME:$PATH' >> /home/ubuntu/.bashrc
  
  # Pull Docker-in-Docker image (pinned version for stability)
  - podman pull docker.io/library/docker:27.3-dind
  
  # Create and start the Docker-in-Podman container (root Podman for privileged support)
  - |
    # Create volume for Docker data persistence
    podman volume create docker-data
    
    # Start Docker-in-Podman container with proper settings for nested containers
    podman run -d \
        --name docker-engine \
        --privileged \
        --cgroupns=host \
        -v docker-data:/var/lib/docker \
        -v /home/ubuntu/workspace:/workspace \
        --restart unless-stopped \
        docker.io/library/docker:27.3-dind \
        dockerd --host=unix:///var/run/docker.sock --host=tcp://0.0.0.0:2375 --tls=false
    
    # Wait for Docker daemon
    sleep 15
    
    # Pre-pull hello-world image
    podman exec docker-engine docker pull hello-world:linux || true
  
  # Enable auto-start of Docker container via systemd service (root)
  - |
    cat > /etc/systemd/system/docker-in-podman.service <<EOF
    [Unit]
    Description=Docker-in-Podman Container
    After=network-online.target
    Wants=network-online.target

    [Service]
    Type=simple
    ExecStartPre=-/usr/bin/podman stop docker-engine
    ExecStartPre=-/usr/bin/podman rm docker-engine
    ExecStart=/usr/bin/podman run --name docker-engine --privileged --cgroupns=host -v docker-data:/var/lib/docker -v /home/ubuntu/workspace:/workspace docker.io/library/docker:27.3-dind dockerd --host=unix:///var/run/docker.sock --host=tcp://0.0.0.0:2375 --tls=false
    ExecStop=/usr/bin/podman stop docker-engine
    Restart=on-failure
    RestartSec=10

    [Install]
    WantedBy=multi-user.target
    EOF
  
  # Enable the service
  - systemctl daemon-reload
  - systemctl enable docker-in-podman.service

final_message: |
  Docker-in-Podman installation complete!
  
  === Usage ===
  SSH: multipass shell docker-in-podman-vm
  
  Docker commands (via wrapper):
    ~/docker --version
    ~/docker run hello-world:linux
    ~/docker ps
  
  Or add to PATH: export PATH=$HOME:$PATH
  Then use: docker run hello-world:linux
  
  === How it works ===
  Podman runs a privileged container with Docker Engine (docker:27.3-dind)
  The ~/docker wrapper executes commands inside that container
